const questions = [
    // 🫧 CONOCERNOS — 40
    { id: 1, category: 'conocernos', text: '¿Qué pequeña cosa puede mejorarte muchísimo un día normal?' },
    { id: 2, category: 'conocernos', text: '¿Qué manía tienes que probablemente descubriría tarde o temprano?' },
    { id: 3, category: 'conocernos', text: '¿Qué plan nunca te da pereza hacer?' },
    { id: 4, category: 'conocernos', text: '¿Qué cosa aparentemente insignificante consigue ponerte de mal humor?' },
    { id: 5, category: 'conocernos', text: '¿Cómo notas que necesitas estar a solas?' },
    { id: 6, category: 'conocernos', text: '¿Qué detalle hace que te sientas especialmente cuidado/a?' },
    { id: 7, category: 'conocernos', text: '¿Qué parte de tu rutina disfrutas más de lo que parece?' },
    { id: 8, category: 'conocernos', text: '¿Qué te cuesta pedir aunque lo necesites?' },
    { id: 9, category: 'conocernos', text: '¿Qué tipo de cumplido te hace más ilusión recibir?' },
    { id: 10, category: 'conocernos', text: '¿Qué haces cuando has tenido un día horrible y solo quieres desconectar?' },
    { id: 11, category: 'conocernos', text: '¿Qué costumbre tuya defenderías aunque todo el mundo dijera que es rarísima?' },
    { id: 12, category: 'conocernos', text: '¿Qué comida podrías repetir varias veces por semana sin cansarte?' },
    { id: 13, category: 'conocernos', text: '¿Eres de necesitar planes con antelación o prefieres decidir sobre la marcha?' },
    { id: 14, category: 'conocernos', text: '¿Qué te ayuda a sentirte cómodo/a cuando estás en un sitio nuevo?' },
    { id: 15, category: 'conocernos', text: '¿Qué canción te sabes demasiado bien?' },
    { id: 16, category: 'conocernos', text: '¿Qué cosa se te da sorprendentemente bien?' },
    { id: 17, category: 'conocernos', text: '¿Qué se te da fatal y has aceptado que probablemente seguirá siendo así?' },
    { id: 18, category: 'conocernos', text: '¿Qué haces diferente cuando tienes muchísima confianza con alguien?' },
    { id: 19, category: 'conocernos', text: '¿Qué tema podría tenerte hablando durante horas?' },
    { id: 20, category: 'conocernos', text: '¿Qué te suele dar vergüenza admitir que te gusta?' },
    { id: 21, category: 'conocernos', text: '¿Qué recuerdo de tu infancia te sigue dando sensación de hogar?' },
    { id: 22, category: 'conocernos', text: '¿Qué olor te transporta inmediatamente a algún momento de tu vida?' },
    { id: 23, category: 'conocernos', text: '¿Qué comportamiento hace que pierdas rápidamente el interés por alguien?' },
    { id: 24, category: 'conocernos', text: '¿Qué característica valoras muchísimo en una amistad?' },
    { id: 25, category: 'conocernos', text: '¿Cómo prefieres que te digan que has hecho algo que ha molestado?' },
    { id: 26, category: 'conocernos', text: '¿Qué necesitas normalmente cuando estás enfadado/a: hablar, espacio, cariño u otra cosa?' },
    { id: 27, category: 'conocernos', text: '¿Hay algo que la gente suele interpretar mal de ti al conocerte?' },
    { id: 28, category: 'conocernos', text: '¿Qué decisión pequeña ha terminado teniendo bastante importancia en tu vida?' },
    { id: 29, category: 'conocernos', text: '¿Qué te hace sentir orgulloso/a de ti últimamente?' },
    { id: 30, category: 'conocernos', text: '¿Qué parte de hacerte mayor te está gustando más de lo que esperabas?' },
    { id: 31, category: 'conocernos', text: '¿Qué parte de hacerte mayor te está gustando bastante menos?' },
    { id: 32, category: 'conocernos', text: '¿Qué capricho pequeño te cuesta muchísimo negarte?' },
    { id: 33, category: 'conocernos', text: '¿Cómo sería para ti un domingo perfecto sin ninguna obligación?' },
    { id: 34, category: 'conocernos', text: '¿Qué cosa necesitas tener más o menos ordenada para sentir que tu vida está bajo control?' },
    { id: 35, category: 'conocernos', text: '¿En qué situaciones aparece tu versión más competitiva?' },
    { id: 36, category: 'conocernos', text: '¿Qué haces cuando alguien te cae mal pero tienes que convivir con esa persona?' },
    { id: 37, category: 'conocernos', text: '¿Qué pequeño lujo cotidiano te hace sentir millonario/a?' },
    { id: 38, category: 'conocernos', text: '¿Qué aprendiste sobre ti en los últimos años que antes no tenías nada claro?' },
    { id: 39, category: 'conocernos', text: '¿Qué situación consigue sacar tu lado más cariñoso?' },
    { id: 40, category: 'conocernos', text: '¿Qué pregunta te gustaría que la gente te hiciera más a menudo?' },

    // ❤️ NOSOTROS — 35
    { id: 41, category: 'nosotros', text: '¿Qué momento nuestro te gustaría poder volver a vivir exactamente igual?' },
    { id: 42, category: 'nosotros', text: '¿Qué fue lo primero de mí que te hizo pensar que aquí podía haber algo?' },
    { id: 43, category: 'nosotros', text: '¿Qué detalle mío has aprendido a apreciar más con el tiempo?' },
    { id: 44, category: 'nosotros', text: '¿En qué momento sientes más que somos un equipo?' },
    { id: 45, category: 'nosotros', text: '¿Qué crees que hacemos especialmente bien como pareja?' },
    { id: 46, category: 'nosotros', text: '¿Qué te gustaría que protegiéramos siempre de nuestra relación aunque cambie todo lo demás?' },
    { id: 47, category: 'nosotros', text: '¿Qué versión de ti aparece cuando estás conmigo y no aparece tanto con otras personas?' },
    { id: 48, category: 'nosotros', text: '¿Qué gesto mío te hace sentir querido/a aunque sea una tontería?' },
    { id: 49, category: 'nosotros', text: '¿Hay algo que ahora entiendes de mí que al principio te costaba comprender?' },
    { id: 50, category: 'nosotros', text: '¿Qué crees que hemos aprendido el uno del otro?' },
    { id: 51, category: 'nosotros', text: '¿Qué recuerdo nuestro te hace sonreír casi automáticamente?' },
    { id: 52, category: 'nosotros', text: '¿Qué crees que necesitamos cada uno cuando discutimos?' },
    { id: 53, category: 'nosotros', text: '¿Qué te gustaría que hiciéramos más a menudo juntos?' },
    { id: 54, category: 'nosotros', text: '¿Qué cosa muy cotidiana contigo se ha convertido en algo especial?' },
    { id: 55, category: 'nosotros', text: '¿Cuándo te has sentido especialmente orgulloso/a de mí?' },
    { id: 56, category: 'nosotros', text: '¿Qué diferencia entre nosotros crees que nos viene bien?' },
    { id: 57, category: 'nosotros', text: '¿Qué diferencia entre nosotros tenemos que aprender a gestionar mejor?' },
    { id: 58, category: 'nosotros', text: '¿Qué te gustaría que nunca diésemos por sentado el uno del otro?' },
    { id: 59, category: 'nosotros', text: '¿Qué cosa puedo hacer para que te resulte más fácil contarme algo difícil?' },
    { id: 60, category: 'nosotros', text: '¿Qué crees que ha cambiado en nosotros desde que empezamos a conocernos?' },
    { id: 61, category: 'nosotros', text: '¿Qué significa para ti sentir seguridad dentro de una relación?' },
    { id: 62, category: 'nosotros', text: '¿Qué momento difícil crees que hemos gestionado especialmente bien?' },
    { id: 63, category: 'nosotros', text: '¿Qué tradición absurda o bonita te gustaría que fuese solo nuestra?' },
    { id: 64, category: 'nosotros', text: '¿Qué cosa de nuestra relación te gustaría poder enseñarle a nuestro yo del primer día?' },
    { id: 65, category: 'nosotros', text: '¿Qué necesitas de mí cuando empiezas a dudar de ti?' },
    { id: 66, category: 'nosotros', text: '¿Qué conversación nuestra recuerdas porque sentiste que realmente te entendí?' },
    { id: 67, category: 'nosotros', text: '¿Qué crees que todavía nos queda por descubrir el uno del otro?' },
    { id: 68, category: 'nosotros', text: '¿Qué cosa que hacemos juntos te gustaría seguir haciendo dentro de muchos años?' },
    { id: 69, category: 'nosotros', text: '¿Cuándo notas que necesitas más atención o cariño de mi parte?' },
    { id: 70, category: 'nosotros', text: '¿Qué te gustaría que recordáramos cuando tengamos una discusión realmente tonta?' },
    { id: 71, category: 'nosotros', text: '¿Qué aspecto de nuestra relación te da más tranquilidad?' },
    { id: 72, category: 'nosotros', text: '¿Qué aventura cotidiana crees que nos representa bastante bien?' },
    { id: 73, category: 'nosotros', text: '¿Qué crees que podría hacer que nuestra relación fuese todavía más fácil de cuidar?' },
    { id: 74, category: 'nosotros', text: '¿Qué has descubierto sobre el amor estando conmigo?' },
    { id: 75, category: 'nosotros', text: 'Si tuvieras que describir lo nuestro sin utilizar la palabra amor, ¿cómo lo describirías?' },

    // 🧠 PROFUNDAS — 35
    { id: 76, category: 'profundas', text: '¿Crees que somos más lo que elegimos o lo que nos ha pasado?' },
    { id: 77, category: 'profundas', text: '¿Puede una persona cambiar de verdad o simplemente aprende a comportarse de otra manera?' },
    { id: 78, category: 'profundas', text: '¿Qué pesa más en una vida: las decisiones importantes o miles de decisiones pequeñas?' },
    { id: 79, category: 'profundas', text: '¿Crees que para perdonar es necesario comprender?' },
    { id: 80, category: 'profundas', text: '¿Hasta qué punto somos responsables de la persona en la que nos convertimos?' },
    { id: 81, category: 'profundas', text: '¿Preferirías conocer una verdad que te haga infeliz o vivir tranquilo/a creyendo algo falso?' },
    { id: 82, category: 'profundas', text: '¿Puede existir una decisión completamente desinteresada?' },
    { id: 83, category: 'profundas', text: '¿Qué diferencia hay para ti entre estar vivo y estar viviendo?' },
    { id: 84, category: 'profundas', text: '¿Cuánto de nuestra personalidad crees que depende de las personas que tenemos alrededor?' },
    { id: 85, category: 'profundas', text: '¿Hay cosas que está bien no superar nunca del todo?' },
    { id: 86, category: 'profundas', text: '¿Crees que todas las personas merecen una segunda oportunidad?' },
    { id: 87, category: 'profundas', text: '¿Qué hace que una vida haya valido la pena?' },
    { id: 88, category: 'profundas', text: '¿Preferirías una vida tranquila y predecible o una intensa aunque implicara más dolor?' },
    { id: 89, category: 'profundas', text: '¿Somos la misma persona que éramos hace diez años si pensamos y sentimos de forma completamente distinta?' },
    { id: 90, category: 'profundas', text: '¿Qué crees que le debemos a las personas que queremos?' },
    { id: 91, category: 'profundas', text: '¿Se puede querer mucho a alguien y aun así decidir que no debe formar parte de tu vida?' },
    { id: 92, category: 'profundas', text: '¿Hasta qué punto entender por qué alguien hizo daño cambia lo que hizo?' },
    { id: 93, category: 'profundas', text: '¿Crees que necesitamos sufrir para valorar realmente las cosas buenas?' },
    { id: 94, category: 'profundas', text: '¿Qué preferirías perder: todos tus recuerdos pasados o la posibilidad de crear recuerdos nuevos?' },
    { id: 95, category: 'profundas', text: '¿Una buena intención puede justificar una mala decisión?' },
    { id: 96, category: 'profundas', text: '¿Qué crees que dice más de alguien: cómo trata a quien quiere o cómo trata a quien no necesita?' },
    { id: 97, category: 'profundas', text: '¿Existe para ti alguna diferencia entre rendirse y saber cuándo dejar ir?' },
    { id: 98, category: 'profundas', text: '¿Cuánto debería sacrificarse una persona por alguien a quien quiere?' },
    { id: 99, category: 'profundas', text: '¿Es posible conocer completamente a otra persona?' },
    { id: 100, category: 'profundas', text: '¿Crees que la felicidad es un estado, una suma de momentos o algo distinto?' },
    { id: 101, category: 'profundas', text: '¿Preferirías ser recordado/a durante siglos o ser profundamente importante para unas pocas personas?' },
    { id: 102, category: 'profundas', text: '¿Cuándo deja una explicación de ser una explicación y empieza a convertirse en una excusa?' },
    { id: 103, category: 'profundas', text: '¿Qué significa para ti ser libre?' },
    { id: 104, category: 'profundas', text: '¿Podemos juzgar justamente una decisión sin haber vivido el contexto de quien la tomó?' },
    { id: 105, category: 'profundas', text: '¿Qué parte de nosotros permanece cuando dejamos de cumplir las expectativas de los demás?' },
    { id: 106, category: 'profundas', text: '¿Es peor hacer daño conscientemente o hacerlo por no haberte parado nunca a pensar?' },
    { id: 107, category: 'profundas', text: '¿Qué crees que necesitamos más: sentir que pertenecemos o sentir que somos libres?' },
    { id: 108, category: 'profundas', text: '¿Puede haber amor sin admiración?' },
    { id: 109, category: 'profundas', text: '¿Crees que existe una versión verdadera de nosotros o somos todas nuestras versiones según el contexto?' },
    { id: 110, category: 'profundas', text: 'Si al final nadie pudiera recordar nada de ti, ¿cambiaría la manera en la que elegirías vivir?' },

    // 🔥 INTIMIDAD — 25
    { id: 111, category: 'intimidad', text: '¿Qué hace que te sientas especialmente deseado/a por alguien?' },
    { id: 112, category: 'intimidad', text: '¿Qué necesitas para sentirte realmente cómodo/a durante el sexo?' },
    { id: 113, category: 'intimidad', text: '¿Qué tipo de iniciativa te gusta que tome la otra persona?' },
    { id: 114, category: 'intimidad', text: '¿Te resulta fácil decir lo que te gusta mientras está pasando?' },
    { id: 115, category: 'intimidad', text: '¿Qué tipo de contacto físico disfrutas especialmente fuera del sexo?' },
    { id: 116, category: 'intimidad', text: '¿Qué te hace sentir más atractivo/a?' },
    { id: 117, category: 'intimidad', text: '¿Prefieres que la intimidad surja espontáneamente o te gusta también poder anticiparla?' },
    { id: 118, category: 'intimidad', text: '¿Hay alguna forma de iniciar el sexo que te resulte especialmente atractiva?' },
    { id: 119, category: 'intimidad', text: '¿Qué importancia tiene para ti el ambiente cuando tenemos intimidad?' },
    { id: 120, category: 'intimidad', text: '¿Qué te ayuda a dejar de pensar en todo lo demás y estar presente durante el sexo?' },
    { id: 121, category: 'intimidad', text: '¿Qué te gusta que ocurra después del sexo?' },
    { id: 122, category: 'intimidad', text: '¿Hay algo que te dé curiosidad probar y nunca hayas planteado?' },
    { id: 123, category: 'intimidad', text: '¿Qué diferencia hay para ti entre sexo y sentir intimidad con alguien?' },
    { id: 124, category: 'intimidad', text: '¿Qué cosas hacen que pierdas las ganas aunque inicialmente las tuvieras?' },
    { id: 125, category: 'intimidad', text: '¿Te gusta hablar durante el sexo? ¿Qué tipo de cosas te gusta escuchar?' },
    { id: 126, category: 'intimidad', text: '¿Hay algún límite que para ti sea especialmente importante que la otra persona conozca?' },
    { id: 127, category: 'intimidad', text: '¿Qué te resulta más excitante: sentirte deseado/a, desear mucho a la otra persona o ambas cosas por igual?' },
    { id: 128, category: 'intimidad', text: '¿Qué papel juega para ti el humor durante la intimidad?' },
    { id: 129, category: 'intimidad', text: '¿Hay alguna inseguridad que pueda aparecer cuando estás desnudo/a con alguien?' },
    { id: 130, category: 'intimidad', text: '¿Cómo prefieres que la otra persona reaccione si algo no te apetece?' },
    { id: 131, category: 'intimidad', text: '¿Qué te hace sentir que puedes experimentar sin sentirte juzgado/a?' },
    { id: 132, category: 'intimidad', text: '¿Qué importancia tiene para ti la frecuencia sexual dentro de una relación?' },
    { id: 133, category: 'intimidad', text: '¿Hay alguna fantasía que te resulte más fácil contar que proponer de verdad?' },
    { id: 134, category: 'intimidad', text: '¿Qué crees que hace que el sexo mejore cuanto más conoces a alguien?' },
    { id: 135, category: 'intimidad', text: '¿Qué te gustaría que yo supiera siempre sobre tu manera de vivir la intimidad?' },

    // 🔮 FUTURO — 25
    { id: 136, category: 'futuro', text: '¿Cómo sería una vida cotidiana en la que sintieras que estás exactamente donde quieres estar?' },
    { id: 137, category: 'futuro', text: '¿Qué cosas te gustaría que ocupasen más espacio en tu vida dentro de cinco años?' },
    { id: 138, category: 'futuro', text: '¿Qué cosas esperas haber dejado atrás dentro de unos años?' },
    { id: 139, category: 'futuro', text: '¿Qué significa para ti tener estabilidad?' },
    { id: 140, category: 'futuro', text: '¿Qué papel te gustaría que tuviera el trabajo en tu vida futura?' },
    { id: 141, category: 'futuro', text: '¿Cómo te gustaría que fuese el lugar al que llamases hogar?' },
    { id: 142, category: 'futuro', text: '¿Qué miedo tienes cuando piensas en hacerte mayor?' },
    { id: 143, category: 'futuro', text: '¿Qué parte de tu vida actual esperas conservar durante muchos años?' },
    { id: 144, category: 'futuro', text: '¿Hay alguna versión futura de ti que te haga especial ilusión conocer?' },
    { id: 145, category: 'futuro', text: '¿Qué te gustaría aprender algún día aunque ahora mismo no sea una prioridad?' },
    { id: 146, category: 'futuro', text: '¿Cómo imaginas tus amistades cuando seas mucho más mayor?' },
    { id: 147, category: 'futuro', text: '¿Te gustaría tener hijos? ¿Qué significa para ti esa decisión?' },
    { id: 148, category: 'futuro', text: '¿Qué tipo de familia te gustaría construir, sea cual sea la forma que tenga?' },
    { id: 149, category: 'futuro', text: '¿Qué cosas necesitarías antes de sentirte preparado/a para formar una familia?' },
    { id: 150, category: 'futuro', text: '¿Cómo te gustaría repartir el tiempo entre pareja, amistades, familia y espacio propio?' },
    { id: 151, category: 'futuro', text: '¿Qué importancia tiene para ti compartir casa con una pareja?' },
    { id: 152, category: 'futuro', text: '¿Qué cosas crees que una pareja debería hablar antes de vivir junta?' },
    { id: 153, category: 'futuro', text: '¿Qué significa para ti comprometerte con alguien a largo plazo?' },
    { id: 154, category: 'futuro', text: '¿Hay algo de tu futuro que no estarías dispuesto/a a abandonar por una relación?' },
    { id: 155, category: 'futuro', text: '¿Qué decisiones importantes crees que una pareja debería tomar siempre conjuntamente?' },
    { id: 156, category: 'futuro', text: '¿Cómo imaginas una convivencia que no termine convirtiéndose únicamente en rutina?' },
    { id: 157, category: 'futuro', text: '¿Qué papel te gustaría que tuviera el dinero en las decisiones de una pareja?' },
    { id: 158, category: 'futuro', text: '¿Cómo te gustaría que nos cuidáramos si algún día uno de los dos atravesara una época realmente difícil?' },
    { id: 159, category: 'futuro', text: '¿Qué cosas te harían pensar que estás construyendo una buena vida con alguien?' },
    { id: 160, category: 'futuro', text: 'Si dentro de muchos años mirásemos atrás, ¿qué te gustaría poder decir de la vida que construimos?' },

    // 😂 GILIPOLLECES — 25
    { id: 161, category: 'gilipolleces', text: 'Si me despertase y tuviese babosas en lugar de dedos y la lengua fuese de piedra, ¿me seguirías queriendo?' },
    { id: 162, category: 'gilipolleces', text: 'Si tuvieras que sustituir tus piernas por las patas de un animal, ¿cuáles elegirías?' },
    { id: 163, category: 'gilipolleces', text: 'Si un fantasma viviera en nuestra casa pero solo hiciera pequeñas putadas, ¿cuánto tardarías en echarlo?' },
    { id: 164, category: 'gilipolleces', text: 'Si mañana fuese ilegal llevar pantalones, ¿cuál sería tu estrategia?' },
    { id: 165, category: 'gilipolleces', text: '¿Qué animal sería el más maleducado si pudiera hablar?' },
    { id: 166, category: 'gilipolleces', text: 'Si pudieras prohibir para siempre una palabra porque te da rabia escucharla, ¿cuál sería?' },
    { id: 167, category: 'gilipolleces', text: 'Si nos persiguiera un asesino y yo me tropezara, ¿me ayudarías o asumirías que mi sacrificio era necesario?' },
    { id: 168, category: 'gilipolleces', text: 'Si solo pudieras comunicarte mediante sonidos de un animal durante una semana, ¿qué animal escogerías?' },
    { id: 169, category: 'gilipolleces', text: '¿Preferirías tener siempre un pelo dentro de la boca o sentir permanentemente que tienes una piedrecita en el zapato?' },
    { id: 170, category: 'gilipolleces', text: 'Si fueras un villano ridículo, ¿cuál sería tu plan para conquistar el mundo?' },
    { id: 171, category: 'gilipolleces', text: '¿Qué objeto cotidiano sería terrorífico si midiera dos metros?' },
    { id: 172, category: 'gilipolleces', text: 'Si intercambiásemos cuerpos durante 24 horas, ¿qué sería lo primero que harías con el mío?' },
    { id: 173, category: 'gilipolleces', text: '¿Preferirías luchar contra una gallina cada vez que abres una puerta o contra un orangután una vez al año sin saber qué día?' },
    { id: 174, category: 'gilipolleces', text: 'Si tuvieras que llevar un objeto completamente inútil como sombrero durante un año, ¿qué elegirías?' },
    { id: 175, category: 'gilipolleces', text: 'Si descubriéramos que uno de los dos es un robot, ¿quién crees que sería y qué prueba lo demostraría?' },
    { id: 176, category: 'gilipolleces', text: '¿Qué delito absurdo crees que cometerías accidentalmente si las leyes fueran muchísimo más específicas?' },
    { id: 177, category: 'gilipolleces', text: 'Si cada vez que entraras en una habitación sonase una canción, ¿cuál sería la peor posible?' },
    { id: 178, category: 'gilipolleces', text: '¿Cuánto dinero tendrían que pagarte para lamer una farola delante de toda tu familia?' },
    { id: 179, category: 'gilipolleces', text: 'Si los muebles pudieran sentir dolor, ¿qué mueble tendría la existencia más desgraciada?' },
    { id: 180, category: 'gilipolleces', text: '¿Qué sería peor: tener rodillas que gritan o codos que se ríen?' },
    { id: 181, category: 'gilipolleces', text: 'Si tuvieses que esconder una jirafa en casa durante una semana, ¿cómo coño lo harías?' },
    { id: 182, category: 'gilipolleces', text: 'Si nuestra relación fuese un producto del supermercado, ¿qué pondría en la etiqueta?' },
    { id: 183, category: 'gilipolleces', text: 'Si los extraterrestres te obligaran a enseñarles una sola cosa para explicarles a los humanos, ¿qué escogerías?' },
    { id: 184, category: 'gilipolleces', text: 'Si pudieras añadir una norma completamente absurda que todo el planeta tuviera que obedecer, ¿cuál sería?' },
    { id: 185, category: 'gilipolleces', text: '¿Qué nombre completamente inapropiado le pondrías a un hijo si no existieran consecuencias?' },

    // 🚬 FUMADÍSIMOS — 15
    { id: 186, category: 'fumadisimos', text: 'Si nuestros gatos pudieran juzgar nuestra relación, ¿qué crees que dirían de nosotros?' },
    { id: 187, category: 'fumadisimos', text: '¿Y si los déjà vu son momentos en los que otra versión nuestra acaba de guardar la partida?' },
    { id: 188, category: 'fumadisimos', text: 'Si pudiéramos fumar un porro con cualquier personaje histórico, ¿quién crees que acabaría diciendo la mayor barbaridad?' },
    { id: 189, category: 'fumadisimos', text: '¿Y si dormir es realmente nuestra vida principal y esto es lo que soñamos cuando allí estamos cansados?' },
    { id: 190, category: 'fumadisimos', text: 'Si pudiéramos meter nuestra relación en un frasco, ¿qué olor tendría?' },
    { id: 191, category: 'fumadisimos', text: '¿Crees que dos personas podrían enamorarse igualmente si cada vez que se mirasen escuchasen mentalmente el sonido de una bocina?' },
    { id: 192, category: 'fumadisimos', text: 'Si todas nuestras células cambian con el tiempo, ¿en qué momento dejamos de ser técnicamente la persona que empezó esta relación?' },
    { id: 193, category: 'fumadisimos', text: 'Si el universo es infinito, ¿hay ahora mismo otra versión nuestra teniendo exactamente esta conversación pero vestidos de langosta?' },
    { id: 194, category: 'fumadisimos', text: '¿Y si los gatos saben perfectamente que existen pero han decidido no participar en la sociedad?' },
    { id: 195, category: 'fumadisimos', text: 'Si pudiéramos fusionarnos durante diez minutos y convertirnos en una sola persona, ¿qué rasgo tuyo y qué rasgo mío dominarían a la criatura?' },
    { id: 196, category: 'fumadisimos', text: 'Si los pensamientos aparecieran durante cinco segundos escritos encima de nuestra cabeza, ¿seguiríamos juntos después de una semana?' },
    { id: 197, category: 'fumadisimos', text: '¿Y si enamorarse es simplemente encontrar a alguien cuya existencia hace que el universo parezca un poco menos absurdo?' },
    { id: 198, category: 'fumadisimos', text: 'Si después de morir descubriéramos que todo esto era un videojuego cooperativo, ¿qué puntuación crees que nos darían como equipo?' },
    { id: 199, category: 'fumadisimos', text: 'Si nuestra casa saliera volando por el espacio y pudiéramos vivir allí para siempre con comida infinita, ¿echarías de menos la Tierra?' },
    { id: 200, category: 'fumadisimos', text: 'Si dentro de cincuenta años estamos juntos, viejos y fumadísimos en un sofá, ¿qué gilipollez crees que seguiremos discutiendo?' }
];